name: Satiros
options:
  deploymentTarget:
    macOS: "14.0"
  usesTabs: true
  indentWidth: 2
  tabWidth: 2

targets:
  Satiros:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Satiros
      - path: Satiros/persistencia
      - path: Satiros/views_auxiliares
      - path: Satiros/componentes
      - path: Satiros/views
    resources:
      - path: Resources
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: satiros.Satiros
        SWIFT_VERSION: 5.0
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: BQ84H65DR2
    dependencies:
      - target: MuralWidget
      - sdk: SwiftUI.framework
      - sdk: SpriteKit.framework
      - sdk: SwiftData.framework
    entitlements:
      path: Satiros/Satiros.entitlements
      properties:
        com.apple.security.app-sandbox: truegit status
        com.apple.security.application-groups:
          - group.satiros.Satiros

  SatirosTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: SatirosTests
    dependencies:
      - target: Satiros

  MuralWidget:
    type: app-extension
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: MuralWidget
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: satiros.Satiros
        SWIFT_VERSION: 5.0
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: BQ84H65DR2
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: WidgetKit.framework
    entitlements:
      generate: true
      path: MuralWidget/MuralWidget.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.application-groups:
          - group.satiros.Satiros
